### PR TITLE
Fix arubaOS-CX power-consumption changes logged

### LINKED ISSUE #3142: HP ArubaOS-CX: power-consumption starting with version FL.10.13.xxxx - permanent power changes logged
Hello dear team,

the ArubaOS-CX switches in Version FL.10.1**3**.xxxx introduce a new sub-command `show environment power-consumption` with the following example output:
```
Power Consumption Averaging Period : 600 seconds

                                    Instantaneous     Average
Name Description                        Power (W)   Power (W)
---------------------------------------------------------------
1    6300M 24SFP+ 4SFP56 Swch               52.00       51.73
```

The parameter `power-consumption` was not available in the previous **L**ong **S**upport **R**elease (**LSR**) Version FL.10.1**0**.xxxx. The Power(W) values always change and produce a new change in odixized every time scanned. I guess this should be easily fixable by doing something like the **fix for the fan** speed in the current version, see commit ed094ff2e93d1ab4627d0cb183d4bd9273745a42 and/or pull-request #2865. I will try to implement this change and create a pull-request if possible.

### PR DESCRIPTION
**Pull request by TerraTalpi**
## Pre-Request Checklist
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description

Fix #3142. The ArubaOS-CX switches with the new **L**ong **S**upport **R**elease (LSR) Version FL.10.1**3**.xxxx introduce a new sub-command `show environment power-consumption`. This displays current power consumption values for all switches in the stack. This is a fix, to exclude all actual power consumption values from the output.

### CODE REVIEW

**Comment by alextremblay** [comment]
Hi @TerraTalpi , I tested out the changes in your PR, and i found that the changes DO work, but leave soemthing to be desired...

it will still produce a "change" if any of the power numbers changes from 2 digits to 3 digits (ie if from one oxidixed run to another, instantaneous power goes from "99.50" to "103.50", then the output after that PR will go from this to this:
```
#    6300M 48SR5 CL6 PoE 4SFP56 Swc      <power>    <power>
#    6300M 48SR5 CL6 PoE 4SFP56 Swc      <power>     <power>
```

also, it doesn't capture or strip total power consumption, so any changes there will still be captured

File: lib/oxidized/model/aoscx.rb [hunk 1]
```diff
@@ -59,6 +59,7 @@ class Aoscx < Oxidized::Model
     cfg.gsub! /^(\d+\/\S+\s+\S+\s+)\d+\.\d+\s+C(.*)/, '\\1<hidden>\\2'
     cfg.gsub! /^(LC.*\s+)\d+\.\d+\s+(C.*)$/, '\\1 <hidden> \\2'
     cfg.gsub! /^(\S+\s+\S+\s+\s+\S+\s+)(slow|normal|medium|fast|max)(\s+\S+\s+\S+\s+)\d+/, '\\1<speed>\\3<rpm>'
+    cfg.gsub! /^(\d+\s+.+\s+)(\s\s\d+\.\d+)(\s+)(\s\s\d+\.\d+)$/, '\\1<power>\\3<power>'
```
Comment (alextremblay) [inline lib/oxidized/model/aoscx.rb:62]: I managed to fix the outstanding issues mentioned in my comment by replacing this line with:

```ruby
    cfg.gsub! /^(\d+\s+.+\s+)(\s\s\d+\.\d+)(\s+)(\s\s\d+\.\d+)$/, '\\1<power>      <power>'
    cfg.gsub! /^Total Power Consumption\s+\d+\.\d+$/, 'Total Power Consumption                  <power>'
```

Comment (TerraTalpi) [reply lib/oxidized/model/aoscx.rb:62]: Hello @alextremblay, thank you very much for your comment and checks. I will enhance regex to match the power consumption for up to a five digit number. My intent with the spaces that I am matching with the regex is, to keep the table formatting and not move / re-align the table row depending on the number of digits captured. I will document this also in the issue.

Comment (TerraTalpi) [reply lib/oxidized/model/aoscx.rb]: I have now updated my regex to adequately replace up to four digit numbers (I guess no single switch can ever consume more than 10k Watts).

Comment (TerraTalpi) [reply lib/oxidized/model/aoscx.rb]: @alextremblay I cannot see any output field "Total Power Consumption" as you stated in the output. Can you provide an example output? Does this only show up with switch stacks as a bottom line?

Comment (TerraTalpi) [reply lib/oxidized/model/aoscx.rb]: Hi @alextremblay, I have now checked the documentation and added support for the 6400, 8400 switch series and chassis switches. I could not find total power consumption anywhere in the output, except with `detail` at the show output. However, I have added this since this may also happen in the future.

**Comment by TerraTalpi** [comment]
Dear maintainers, ready to merge from my side, I have vastly expanded support for multiple arubaOS-CX switch series and chassis switches. For details, see related issue with the deeper analysis of the outputs that may come and must be parsed.

**Comment by robertcheramy** [comment]
@alextremblay - does the PR now works for you?

**Comment by TerraTalpi** [comment]
Hi @robertcheramy thank you for approving the CI/CD runs. I have corrected the trailing whitespaces error, sorry for that. Please run the tests again in order for all tests to pass.

**Comment by robertcheramy** [comment]
@alextremblay - I will merge this PR. If you miss something, this can be changed / added afterwards.
